server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

jwt:
  secret: "fvtpE9CIsCfnHJx7tpIXeB3chpKrIImW2XpfDB0q+J4="

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
